apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ppj2n1ymg-python 
  janus-idp.io/tekton: ppj2n1ymg-python
  backstage.io/kubernetes-id: ppj2n1ymg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppj2n1ymg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml